# Generated by Django 6.0.6 on 2026-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('opening_status', models.CharField(choices=[('open', '営業中'), ('closed', '本日休み'), ('preparing', '準備中')], default='preparing', max_length=20)),
                ('stock_status', models.CharField(choices=[('available', '在庫あり'), ('low', '残り少ない'), ('sold_out', '売り切れ')], default='available', max_length=20)),
                ('today_menu', models.TextField(blank=True, max_length=1000)),
                ('special_notice_enabled', models.BooleanField(default=False)),
                ('special_notice', models.TextField(blank=True, max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
