# Generated by Django 6.0.6 on 2026-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '店舗', 'verbose_name_plural': '店舗'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='店舗説明'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_status',
            field=models.CharField(choices=[('open', '営業中'), ('closed', '本日休み'), ('preparing', '準備中')], default='preparing', max_length=20, verbose_name='営業状況'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='special_notice',
            field=models.TextField(blank=True, max_length=1000, verbose_name='今だけ情報'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='special_notice_enabled',
            field=models.BooleanField(default=False, verbose_name='今だけ情報公開'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='stock_status',
            field=models.CharField(choices=[('available', '在庫あり'), ('low', '残り少ない'), ('sold_out', '売り切れ')], default='available', max_length=20, verbose_name='在庫状況'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='today_menu',
            field=models.TextField(blank=True, max_length=1000, verbose_name='本日のメニュー'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日時'),
        ),
    ]
